### ISSUE TITLE
"You may need an appropriate loader to handle this file type", a loader problem?

### ISSUE THREAD

**Issue by TaeYeopKim** [WrathChaos/react-native-poll#9]
```
Uncaught Error: Module parse failed: Unexpected token (11:20)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         };
|     }
>     bounceAnimation = (value, velocity, bounciness) => {
|         const { useNativeDriver = true } = this.props;
|         Animated.spring(this.state.bounceValue, {
    at ./node_modules/@freakycoder/react-native-bounceable/build/dist/RNBounceable.js (wrapNativeSuper.js:31:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-poll/build/dist/components/RNPollItem.js (RNPollItem.tsx:13:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/react-native-poll/build/dist/RNPoll.js (RNPoll.tsx:7:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (bootstrap:856:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (log.js:59:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1
```

I'm using Expo and using this poll library. Works well in iOS(did not test with android yet), but gives me this loader error when trying to view with Web.
Pretty new with all of the react-native world, could I ask for some help?

I did see the closed issue at the react-native-bounceable repo(https://github.com/WrathChaos/react-native-bounceable/issues/1), but wasn't able to get much from it.

**Comment by kuraydev** [comment]
Hello @TaeYeopKim 
Really sorry for the extremely late response. 

I suppose you're trying to run these libraries with Web not just react native? 

Unfortunately, I do not have any experience with `react-native-web` so I cannot support it. If it is another problem please tag me we can take a look at it however, I am using these library multiple production applications and I could not reproduce this issue
